Add Locale Support to Hyprlauncher
hyprutils/hyprlauncher pull request #166
Opened 2024-12-15 22:10 UTC by luyu-wu

Now correctly reads locale params from destop entries.

Before:
![image](https://github.com/user-attachments/assets/c001bdc4-974f-49d3-987e-886abf005bfe)

After:
![image](https://github.com/user-attachments/assets/fe105b01-36ed-470e-ae86-6b9b9f693311)

2024-12-15 22:38 UTC, adamperkowski requested changes

2024-12-15 22:38 UTC, adamperkowski commented on src/launcher.rs
> +	        // fall back
```suggestion
```

2024-12-15 22:38 UTC, adamperkowski commented on src/launcher.rs
> +	    }
```suggestion
		if section.has_attr_with_param(base_key, lang) {
            section.attr_with_param(base_key, lang).map(String::from)
        } else {
            // fall back
            section.attr(base_key).map(String::from)
        }
```

2024-12-15 22:38 UTC, adamperkowski commented on src/launcher.rs
> +
```suggestion
```

2024-12-15 22:44 UTC, adamperkowski approved these changes
thanks. let's wait for @nnyyxxxx

2024-12-16 03:11 UTC, nnyyxxxx approved these changes

2024-12-16 03:11 UTC, merged