Add calculation functionality
hyprutils/hyprlauncher pull request #88
Opened 2024-11-18 09:03 UTC by BardiyaFeili

Hello,

Most launchers have a calculation functionality to quickly calculate equations and copy them to the clipboard.

My code uses the [evalexpr](https://crates.io/crates/evalexpr) crate to to the calculations and wl-copy to copy the result to the clipboard. wl-copy is available as wl-clipboard in most distros' repos.

you can enter calculation mode but typing '=' and then you can enter your expression. Pressing 'enter' on the result will copy it to the clipboard using the `wl-copy -t text/plain "result"`.

I was not exactly sure how the score system works but the rest of the app is working as intended so there doesn't seem to be a problem.

I also did not know how to put a calculator icon for the result so right no there is no icon.

This is my first pr so If there are any issues with the code please tell me so I can fix them.

2024-11-18 09:13 UTC, nnyyxxxx requested changes
needs to support xclip, needs to be togglable in the config file, needs a configuration.md change to accommodate that, and needs to be off by default

2024-11-18 09:26 UTC, BardiyaFeili commented
What should the category for it in the configuration be called.
Is "Modes" good or something else?

2024-11-18 09:42 UTC, nnyyxxxx commented
> What should the category for it in the configuration be called? Is "Modes" good or something else?

yes modes is fine, eventually we will add drun run and dmenu modes as well, so its perfect

2024-11-19 13:37 UTC, BardiyaFeili commented
I've tried doing something like this and some other things but they don't work.

```rust
Command::new("sh")
    .arg("-c")
    .arg(format!("echo {} | xclip -i", &app.name))
    .spawn()
    .unwrap();
```
The reason is rust gives the arguments to sh without quotes but quotes are required for the pipe which is the only way I found to copy something to xclip

2024-11-19 18:35 UTC, abenz1267 commented
Using `evalexpr` is inferior to what other launchers do. Krunner, Walker, pop-launcher etc. all use `libqalculate`. In Rust you'd try to use `Rink`, as f.e. Anyrun is doing.

Anything else isn't adequate.

2024-11-19 18:42 UTC, abenz1267 commented
> I've tried doing something like this and some other things but they don't work.
> 
> ```rust
> Command::new("sh")
>     .arg("-c")
>     .arg(format!("echo {} | xclip -i", &app.name))
>     .spawn()
>     .unwrap();
> ```
> 
> The reason is rust gives the arguments to sh without quotes but quotes are required for the pipe which is the only way I found to copy something to xclip

https://doc.rust-lang.org/std/process/index.html#handling-io

2024-11-19 19:55 UTC, BardiyaFeili commented
> Using `evalexpr` is inferior to what other launchers do. Krunner, Walker, pop-launcher etc. all use `libqalculate`. In Rust you'd try to use `Rink`, as f.e. Anyrun is doing.
> 
> Anything else isn't adequate.

I had a look at it and it looks like it will be better than the evalexpr crate I was using. 

I will switch to it tomorrow.

2024-11-22 07:06 UTC, abenz1267 commented
What's the state here? Last commit was 4 days ago.

2024-11-22 08:17 UTC, BardiyaFeili commented
> What's the state here? Last commit was 2 days ago.

I have been busy for a few days. I think that I will have time to work on this on Sunday.

2024-11-22 08:22 UTC, abenz1267 commented
> > What's the state here? Last commit was 2 days ago.
> 
> I have been busy for a few days. I think that I will have time to work on this on Sunday.

I just wasn't sure, because the last thing you wrote was about switching to Rink, which i thought happened in the last commit. No worries.

2024-11-22 09:03 UTC, BardiyaFeili commented
> I just wasn't sure, because the last thing you wrote was about switching to Rink, which i thought happened in the last commit. No worries.

The switch to rink is complete and the calculator if working fine right now, The only thing left is supporting xclip.

2024-12-02 09:09 UTC, abenz1267 commented
> The implementation may be harder, but I was wondering maybe using qalculator may be a better option as it has a better OOB experience with more built in functions and units? Just a thought
> 
> The CLI "qcalc" seems to be a good starting point, taking in the input and outputting its interpretation and the answer. And if the user selects the result to copy, copy-friendly version can be obtained with `qcalc -t`

The implementation isn't really that much harder. Personally using rink for simplicity... is ok. But using libqalculate would be better. That's what Krunner, Walker and other runners also user. So people are already familiar with that.

2024-12-02 12:35 UTC, BardiyaFeili commented
> conflicts need fixing, due to: #114

Fixed all of them

2024-12-02 12:55 UTC, BardiyaFeili commented
Although building the app is currently failing because of the changes that were made to the code base.

2024-12-02 18:03 UTC, BardiyaFeili commented
The calculator is working again, There are still some bugs and problems which I will fix as soon as I can.

2024-12-03 02:14 UTC, nnyyxxxx commented
more conflicts

2024-12-04 22:08 UTC, nnyyxxxx requested changes

2024-12-04 22:08 UTC, nnyyxxxx commented on configuration.md
> +
This doesn't look correct, header should be "Calculator Mode". More documentation is needed as well, like the modes below.

2024-12-04 22:13 UTC, nnyyxxxx requested changes

2024-12-04 22:13 UTC, nnyyxxxx commented on src/search.rs
> +                    results.push(create_calc_entry(&query));
this is only checking if the first character is a digit, PR description is misleading.

2024-12-04 22:13 UTC, nnyyxxxx commented on src/search.rs
> +const BONUS_SCORE_CALC: i64 = 3000;
``BONUS_SCORE_CALC`` is not being used properly, see ``=`` review below

2024-12-04 22:16 UTC, nnyyxxxx requested changes

2024-12-04 22:16 UTC, nnyyxxxx commented on src/search.rs
> +            icon_name: String::from("calculator"),
```suggestion
            icon_name: String::from("accessories-calculator"),
```

2024-12-04 22:17 UTC, nnyyxxxx commented on src/search.rs
> +            icon_name: String::from("calculator"),
this fixes the icon issue

2024-12-04 22:17 UTC, nnyyxxxx commented on src/search.rs
> +            icon_name: String::from("calculator"),
![image](https://github.com/user-attachments/assets/88a80fee-98db-4a89-9cc9-074e95f9c5c3)

2024-12-04 22:40 UTC, nnyyxxxx commented on src/search.rs
> +            icon_name: String::from("calculator"),
why was this marked as resolved?

2024-12-04 22:40 UTC, BardiyaFeili commented on src/search.rs
> +                    results.push(create_calc_entry(&query));
I have changed the way how entering the calculator mode works. I will also change the documentation accordingly.

2024-12-04 23:01 UTC, nnyyxxxx approved these changes
lgtm

@adamperkowski review

2024-12-04 23:18 UTC, nnyyxxxx requested changes
https://github.com/hyprutils/hyprlauncher/actions/runs/12169684976/job/33944238886?pr=88

fix spelling mistakes

2024-12-04 23:22 UTC, nnyyxxxx requested changes
https://github.com/hyprutils/hyprlauncher/commit/5a378f4ef6849716033ed5bd558eba655a68d5be

with this commit, the new category will have to get added to ``let required_categories``

2024-12-05 05:57 UTC, nnyyxxxx approved these changes

2024-12-05 05:58 UTC, merged